MaxTime=180
QueueName=msg.queueBoth
BrokerURL=ssl://b-c9ad1948-dd0c-4b27-ae72-f246eb402ab7-1.mq.us-east-1.amazonaws.com:61617
BrokerUsername=admin
BrokerPassword=adminadminadmin
ValidCsvFile=valid.csv
InvalidCsvFile=invalid.csv
ProducersCount=2
ConsumersCount=2
